const products = [
    {
        id: 1,
        name: "Wireless Headphones",
        productdesc: "Noise-cancelling over-ear headphones with deep bass.",
        price: "1599 RS",
        rating: 4.5,
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcS-qWKjwM7P0OvQ6-EX6ZcSLoAXq2KZAh-zIojahEYQP7xYgzURnZAjJQCG2e_yawQ5d3iDdG61by_oO0tqyxcwXlvSb9xq5AzUZB4HDbx3QK3ly6MgGT1a1Q",
    },
    {
        id: 2,
        name: "Smartphone",
        productdesc: "Sleek and powerful with a stunning display.",
        price: "89,999 RS",
        rating: 4.7,
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSJK2uTs4XaCkxEyZ4GBTv23xOmFtth3EBz7doMhS9bYLnibH-Qn6ahSrkSRW_sN4J7guu1o8AMzSbx9KG2xiNjVOc0i8oFIFmVNrzk2-iIqzcWWxOyD3js",
    },
    {
        id: 3,
        name: "Gaming Laptop",
        productdesc: "High-performance laptop for gaming and productivity.",
        price: "$1299.99",
        rating: 4.8,
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQa1AEcjRM1XFSkZ5r6b6gD7y16P9mb_liE8K63cb92_5m-oZvtVM_5ebmIFT3j4ZwCRDrNGcNQajY7tQacsxM0ljIGchZnFYmHRnhYV1B5xRQb9kW1kQ0I",
    },
    {
        id: 4,
        name: "Smartwatch",
        productdesc: "Track your fitness and stay connected on the go.",
        price: "$199.99",
        rating: 4.3,
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRuIKIb4FIkjrsgieuCmDIZPql_XwxM-U0TudGUfkp-DR5bXe9cyJSbItZzjNUDlcNYT65vpwg1O_PcslG9uWuRzMGcvNiTFc9grLk6gvVEUmPT6ZpXk_zlUg&usqp=CAE",
    },
    {
        id: 5,
        name: "Bluetooth Speaker",
        productdesc: "Portable speaker with exceptional sound quality.",
        price: "$49.99",
        rating: 4.6,
        image: "https://m.media-amazon.com/images/I/81fkcBjZndL._SL1500_.jpg",
    },
    {
        id: 6,
        name: "4K Action Camera",
        productdesc: "Capture your adventures in stunning 4K resolution.",
        price: "$299.99",
        rating: 4.4,
        image: "https://m.media-amazon.com/images/I/51JwcRWiefL._SL1080_.jpg",
    },
    {
        id: 7,
        name: "Fitness Tracker",
        productdesc: "Keep track of your steps, calories, and heart rate.",
        price: "$89.99",
        rating: 4.2,
        image: "https://m.media-amazon.com/images/I/313oLK-s80L.jpg",
    },
    {
        id: 8,
        name: "Wireless Keyboard",
        productdesc: "Ergonomic and lightweight keyboard for daily use.",
        price: "$39.99",
        rating: 4.1,
        image: "https://m.media-amazon.com/images/I/81N2AnA91nL._SL1500_.jpg",
    },
    {
        id: 9,
        name: "Wireless Keyboard",
        productdesc: "Ergonomic and lightweight keyboard for daily use.",
        price: "$39.99",
        rating: 4.1,
        image: "https://m.media-amazon.com/images/I/81N2AnA91nL._SL1500_.jpg",
    },
    {
        id: 10,
        name: "Wireless Keyboard",
        productdesc: "Ergonomic and lightweight keyboard for daily use.",
        price: "$39.99",
        rating: 4.1,
        image: "https://m.media-amazon.com/images/I/81N2AnA91nL._SL1500_.jpg",
    }
];

export default products;
